- hosts: flask_app
  become: true
  gather_facts: false
  tasks:
  - include_tasks: includes/install_python.yml

- hosts: flask_app
  become: true
  vars_files:
  - vars/flask_app.yml
  roles:
  - machine.frontend
